### PR TITLE
Minor tweaks, bump version and update README.md

### PR DESCRIPTION
**Pull request by khellang**
@thecodejunkie This zip should be uploadable directly 😄

[github.expandinizr v2.0.2.zip](https://github.com/thecodejunkie/github.expandinizr/files/4829854/github.expandinizr.v2.0.2.zip)

### CODE REVIEW

**Comment by thecodejunkie** [comment]
@khellang I'll take a look at this tonight! I wasn't online much over the weekend and been a busy workday! ❤️

**Comment by hoshsadiq** [comment]
Any updates on this?

**Comment by thecodejunkie** [comment]
I hope to get this done tomorrow. The Chrome Extension store updated their publishing requirements so we have to provide some additional information when publishing a new version

**Comment by hoshsadiq** [comment]
No problem. If you can't get it done soon, any chance this PR can get merged sooner rather? I use this as a user style, so I can get a build going quicker.

**Comment by khellang** [comment]
Merged 😄 We don't have to leave this PR open to get it pushed 😉

**Comment by hoshsadiq** [comment]
Thank you sir!

**Comment by thecodejunkie** [comment]
v2.0.2 has now been reviewed by Google and published in the Chrome extension store

**Pull request merged**
