### PR TITLE
Version bump and release notes

### PR DESCRIPTION
**Pull request by khellang**
Let's finally :shipit:

### CODE REVIEW

**Comment by khellang** [comment]
@thecodejunkie Did you ever get to test-drive this puppy?

**Comment by thecodejunkie** [comment]
I _think_ it's the version I've been running for a while now. Let me install the latest commit on my machine and try, I'm almost certain I've spotted some wrapping of the side bar when creating a new pull-request

**Comment by thecodejunkie** [comment]
@khellang yep! Noticed there's a security vulnerability that we can fix by bumping the version https://github.com/thecodejunkie/github.expandinizr/network/dependencies

I'll also take a look at the `PR -> split view` problem .. should get some time to take a look at these things tonight

**Comment by thecodejunkie** [comment]
Briefly looked at this (too damn warm to code right now!) but when you toggle the split diff, it adds the `full-width` class, to the body, which causes `new-pr-form` to get a `max-width` of `980px` and 
the div with class `container new-discussion-timeline experiment-repo-nav` gets `padding-right: 20px; padding-left: 20px; `. Removing these two seems to do the trick.

@khellang can you devtools verify this? 😄

**Comment by thecodejunkie** [comment]
@khellang did you get a chance to test the fix? ❤️

**Comment by khellang** [comment]
No, I didn't even realize there was a fix. Everything looks good here 🤷‍♂️

**Comment by thecodejunkie** [comment]
@khellang u mean it looks good with the fix or without applying anything?

**Comment by khellang** [comment]
Without the fix 😊

**Comment by thecodejunkie** [comment]
@khellang hmm, with the version u sent me a while back.. I still get this on a PR with a split diff view

image

that screenshot was taken second ago. This is on 1920x1080

**Comment by khellang** [comment]
Ouch. Yeah, that's no good. I guess I need to take a look at which version I'm running 😂

**Comment by khellang** [comment]
OK, think I fixed it ✨

**Comment by khellang** [comment]
[github.expandinizr v2.0.0.zip](https://github.com/thecodejunkie/github.expandinizr/files/2169444/github.expandinizr.v2.0.0.zip)

^ if you want to test it 😄

**Comment by thecodejunkie** [comment]
❤️ will take it for a spin after a couple of meetings 😒

**Comment by thecodejunkie** [comment]
@khellang that seems to have done the trick! Will bake a new version, in the extension store, tonight!

**Comment by khellang** [comment]
@thecodejunkie Did you get to ship this?

**Comment by khellang** [comment]
Hey @thecodejunkie! You alive? 🤔

**Comment by khellang** [comment]
anybody home?

**Pull request merged**
