### PR TITLE
Page Action to toggle the styling from this extension

### PR DESCRIPTION
**Pull request by khellang**
Experimented a bit with a Chrome page action to completely remove the styling this extension adds. It does this by toggling a top-level `expandinizr` css class.

This can be useful if you want to see how others without the extension sees your comments. See screencast: http://screencast.com/t/vTWvCjomX9

### CODE REVIEW

**Comment by khellang** [comment]
@ccampanale I think I need some input here...

The way you implemented GH Enterprise support was by adding new permissions, right?

How could we get the URLs from these permissions in [here](https://github.com/thecodejunkie/github.expandinizr/pull/58/files#diff-961641dd6af66f5e3313307cf4eb8f1dR76)? Ideally, this button should work for the same sites.

**Comment by ccampanale** [comment]
Yeah, so adding sites in the options page adds `Chrome.Permissions.Origins`. You can read more about adding/removing/etc for those permissions dynamically [here](https://developer.chrome.com/extensions/permissions).

You can check out how we are pulling the permissions and options and populating the options form [here](https://github.com/khellang/github.expandinizr/blob/toggle-browser-action/src/options.js#L10#L67) as well and that may be able to help.

I'm not sure that necessarily answers the question but it might start you down the right path. Let me know what you think.

**Comment by khellang** [comment]
Alright. I think this is ready :smile:

**Comment by khellang** [comment]
@thecodejunkie It would be cool if you took it for a test drive for a couple of days, just to make sure everything is smooth 😄

**Comment by khellang** [comment]
OK, we should get this in... I just updated this branch and took it for a spin. Looks pretty good. And nice to be able to disable the plugin.

**Pull request merged**
